from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path
from typing import Any

from strapi_utils import (
    coerce_scalar,
    data_dir,
    default_export_path,
    is_scalar,
    json_dumps,
    node_type_for_type,
    project_root,
    sanitize_identifier,
    table_name_for_type,
)


def load_export(path: Path) -> dict[str, list[dict[str, Any]]]:
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError("Expected top-level JSON object keyed by Strapi content type")
    return data


def table_columns(records: list[dict[str, Any]]) -> list[str]:
    columns = {"id", "source_type", "raw_json"}
    for record in records:
        for key, value in record.items():
            col = sanitize_identifier(key)
            columns.add(col)
            if not is_scalar(value):
                columns.add(f"{col}_json")
    ordered = ["id", "source_type", "raw_json"]
    for col in sorted(columns - set(ordered)):
        ordered.append(col)
    return ordered


def sqlite_type_for_column(column: str) -> str:
    if column == "id":
        return "INTEGER PRIMARY KEY"
    if column.endswith("_count"):
        return "INTEGER"
    if column.endswith("_at") or column.endswith("_date"):
        return "TEXT"
    return "TEXT"


def create_table(cursor: sqlite3.Cursor, table_name: str, columns: list[str]) -> None:
    col_sql = ",\n  ".join(f'"{c}" {sqlite_type_for_column(c)}' for c in columns)
    cursor.execute(f'CREATE TABLE IF NOT EXISTS "{table_name}" (\n  {col_sql}\n);')


def normalize_row(record: dict[str, Any], content_type: str) -> dict[str, Any]:
    row: dict[str, Any] = {
        "id": record.get("id"),
        "source_type": node_type_for_type(content_type),
        "raw_json": json_dumps(record),
    }
    for key, value in record.items():
        col = sanitize_identifier(key)
        if is_scalar(value):
            row[col] = coerce_scalar(value)
        else:
            row[f"{col}_json"] = json_dumps(value)
    return row


def insert_rows(cursor: sqlite3.Cursor, table_name: str, columns: list[str], rows: list[dict[str, Any]]) -> None:
    placeholders = ", ".join(["?"] * len(columns))
    col_sql = ", ".join(f'"{c}"' for c in columns)
    sql = f'INSERT OR REPLACE INTO "{table_name}" ({col_sql}) VALUES ({placeholders})'
    for row in rows:
        cursor.execute(sql, [row.get(c) for c in columns])


def write_schema(schema_path: Path, tables: dict[str, list[str]]) -> None:
    lines = [
        "-- Auto-generated relational schema for URDABAI Strapi export",
        "-- Generated by src/import_relational.py",
        "",
    ]
    for table_name in sorted(tables.keys()):
        cols = tables[table_name]
        lines.append(f'CREATE TABLE IF NOT EXISTS "{table_name}" (')
        for i, col in enumerate(cols):
            comma = "," if i < len(cols) - 1 else ""
            lines.append(f'  "{col}" {sqlite_type_for_column(col)}{comma}')
        lines.append(");")
        lines.append("")
    schema_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Import Strapi export into SQLite")
    parser.add_argument("--input", type=Path, default=default_export_path())
    parser.add_argument("--database", type=Path, default=data_dir() / "urdaibai.db")
    parser.add_argument("--schema", type=Path, default=project_root() / "schema.sql")
    args = parser.parse_args()

    export_data = load_export(args.input)
    args.database.parent.mkdir(parents=True, exist_ok=True)

    table_defs: dict[str, list[str]] = {}
    table_rows: dict[str, list[dict[str, Any]]] = {}
    for content_type, records in export_data.items():
        table_name = table_name_for_type(content_type)
        cols = table_columns(records)
        table_defs[table_name] = cols
        table_rows[table_name] = [normalize_row(r, content_type) for r in records]

    with sqlite3.connect(args.database) as conn:
        cur = conn.cursor()
        for table_name, cols in table_defs.items():
            create_table(cur, table_name, cols)
            insert_rows(cur, table_name, cols, table_rows[table_name])
        conn.commit()

    write_schema(args.schema, table_defs)
    print(f"Created database: {args.database}")
    print(f"Wrote schema SQL: {args.schema}")


if __name__ == "__main__":
    main()
